### ISSUE TITLE
Is support for final versions of NIST algorithms planned?

### ISSUE THREAD

**Issue by ralienpp** [aabmets/quantcrypt#10]
NIST recently published FIPS 203, 204 and 205, with finalized versions of the signature and KEM PQ algorithms. Will this library be updated to expose these algorithms?

**Comment by aabmets** [comment]
> NIST recently published FIPS 203, 204 and 205, with finalized versions of the signature and KEM PQ algorithms. Will this library be updated to expose these algorithms?

My expectation is to move this library to support the final versions of the PQC algorithms, but this is entirely dependant on the PQClean project, or if they will not update their code, then I'll need to find another C source which could be compiled with FFI for Python.
