### ISSUE TITLE
ARM installation breaking

### ISSUE THREAD

**Issue by humbertowoody** [aabmets/quantcrypt#3]
Hello! First of all, thanks for this library.

I'm trying to run it on an ARM-based VM on AWS, for some reason on x86 and my local M1 works perfectly, however, on this ARM device it installs correctly but on the attached screenshot you can see the error: 

```
Quantcrypt Fatal Error:
Unable to continue due to missing CLEAN binaries.
```

![Screenshot 2024-02-13 at 19 30 07](https://github.com/aabmets/quantcrypt/assets/8785685/d9be884c-d46c-43c8-a1bb-32d0a1bcea52)

In my ignorance, I assume that I'm missing a step to compile the binaries under my current architecture since they are incompatible.  Am I missing something else?  I'm installing the same project on the three machines using pyenv for the Python version, and on the other two devices steps used in the capture work as intended but on this particular machines it just fails. I also noticed the same behavior on Docker by using the `python:3.12` base image but assumed it had something to do with Docker itself, mentioning it in case it's worth something. Thanks in advance!

**Comment by aabmets** [comment]
QuantCrypt is unable to support the ARM architecture at the moment, as that would require the compilation of the PQClean source code on an ARM architecture host device, or using some compatibility flags in clang or GCC to support aarch64. A contribution on this issue would be very welcome, as I don't know yet how to compile the PQClean source code to support the AVX2 instruction set nor the ARM architecture for QuantCrypt on GitHub Actions. Technically, it should be feasible, as PQClean has the C code for it, but I don't know how to make it work with QuantCrypt.

**Comment by embetrix** [comment]
that will be a very interesting feature, I would help if you guide me how the PQClean binaries are integrated here ?
